name: CI/CD for ClothesCast Frontend

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 실행

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies & Build
        run: |
          npm ci  # npm install보다 빠름
          npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build

  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3  # ✅ 최신 버전 사용
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64  # 단일 플랫폼으로 최적화
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest
          cache-to: type=inline  # 빌드 캐싱

  deploy:
    name: Deploy to Dev Server
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH Private Key  # ✅ SSH 키를 안전하게 디코딩
        run: echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" | base64 --decode > private_key && chmod 600 private_key

      - name: SSH and Deploy to Dev Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: private_key
          script: |
            echo "Stopping existing container..."
            docker stop clothcast-frontend || true
            docker rm clothcast-frontend || true

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest

            echo "Running new container on port 80..."
            docker run -d --name clothcast-frontend -p 3000:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest