name: Deploy clothcast-frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest

      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}clothcast-frontend:latest
            docker stop clothcast-frontend || true
            docker rm clothcast-frontend || true
            docker run -d --name clothcast-frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest