name: Deploy clothcast-frontend

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest .

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest

      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app-frontend

            # 기존 컨테이너 중지 및 삭제
            docker stop clothcast-frontend || true
            docker rm clothcast-frontend || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest || true

            # 최신 이미지 Pull 후 실행
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest
            docker run -d --name clothcast-frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/clothcast-frontend:latest